export const FOOD_CATEGORY_LIST_REQUEST = "FOOD_CATEGORY_LIST_REQUEST";
export const FOOD_CATEGORY_LIST_SUCCESS = "FOOD_CATEGORY_LIST_SUCCESS";
export const FOOD_CATEGORY_LIST_FAIL = "FOOD_CATEGORY_LIST_FAIL";

export const FOOD_CATEGORY_DETAILS_REQUEST = "FOOD_CATEGORY_DETAILS_REQUEST";
export const FOOD_CATEGORY_DETAILS_SUCCESS = "FOOD_CATEGORY_DETAILS_SUCCESS";
export const FOOD_CATEGORY_DETAILS_FAIL = "FOOD_CATEGORY_DETAILS_FAIL";
