export const RECIPE_LIST_REQUEST = "RECIPE_LIST_REQUEST";
export const RECIPE_LIST_SUCCESS = "RECIPE_LIST_SUCCESS";
export const RECIPE_LIST_FAIL = "RECIPE_LIST_FAIL";

export const RECIPE_DETAILS_REQUEST = "RECIPE_DETAILS_REQUEST";
export const RECIPE_DETAILS_SUCCESS = "RECIPE_DETAILS_SUCCESS";
export const RECIPE_DETAILS_FAIL = "RECIPE_DETAILS_FAIL";

export const RECIPE_CREATE_REVIEW_REQUEST = "RECIPE_CREATE_REVIEW_REQUEST";
export const RECIPE_CREATE_REVIEW_SUCCESS = "RECIPE_CREATE_REVIEW_SUCCESS";
export const RECIPE_CREATE_REVIEW_FAIL = "RECIPE_CREATE_REVIEW_FAIL";
export const RECIPE_CREATE_REVIEW_RESET = "RECIPE_CREATE_REVIEW_RESET";

export const RECIPE_CREATE_REQUEST = "RECIPE_CREATE_REQUEST";
export const RECIPE_CREATE_SUCCESS = "RECIPE_CREATE_SUCCESS";
export const RECIPE_CREATE_FAIL = "RECIPE_CREATE_FAIL";
export const RECIPE_CREATE_RESET = "RECIPE_CREATE_RESET";

export const RECIPE_MY_LIST_REQUEST = "RECIPE_MY_LIST_REQUEST";
export const RECIPE_MY_LIST_SUCCESS = "RECIPE_MY_LIST_SUCCESS";
export const RECIPE_MY_LIST_FAIL = "RECIPE_MY_LIST_FAIL";
export const RECIPE_MY_LIST_RESET = "RECIPE_MY_LIST_RESET";
